version: "3"
services:
  docker-playground-v2ray:
    image: v2fly/v2fly-core:latest
    container_name: docker-playground-v2ray
    restart: unless-stopped
    # 将日志大小限制为 1M，以防止硬盘空间不足
    logging:
      driver: json-file
      options:
        max-size: 1m
    ports:
      - 9001:9001
    # 加入指定网络
    networks:
      -  MyNetwork
    volumes:
      - ./config:/etc/v2ray

  docker-playground-v2ray-web:
    image: docker-playground-v2ray-web:latest
    container_name: docker-playground-v2ray-web
    restart: unless-stopped
    # 设定上下文根目录，然后以该目录为准指定 Dockerfile，赋值Dockerfile 中的 ARG 指令
    build: 
      context: .
      dockerfile: Dockerfile
    # 将日志大小限制为 1M，以防止硬盘空间不足
    logging:
      driver: json-file
      options:
        max-size: 1m
    command: --port 9002 --ipv6        
    ports:
      - 9002:9002
    # 加入指定网络
    networks:
      -  MyNetwork
    volumes:
      - ./config:/var/www/html/config
    depends_on:
      - docker-playground-v2ray      

networks:
  MyNetwork:
    external: true

# docker-compose build --no-cache
# docker-compose up -d 