version: '3.1'

services:
  mariadb:
    image: mariadb
    container_name: mariadb
    restart: unless-stopped
    networks:
      - MyNetwork
    # 以 Compose 配置文件为中心的相对路径作为数据卷挂载到容器。
    volumes:
    - ./data:/var/lib/mysql
    # - ./conf:/etc/mysql/conf.d
    # - ./my.cnf:/etc/mysql/my.cnf
    ports:
      - '3307:3306'
    environment:
      TZ: Asia/Shanghai
      MARIADB_ROOT_PASSWORD: '123456'

networks:
  MyNetwork:
    external: true
# docker-compose build --no-cache
# docker-compose up -d

# 用户名 root
# 密码 123456