version: '3'
services:
  redis:
    # 镜像名称
    image: redis:latest
    # 容器名称
    container_name: redis
    # 自启动
    restart: unless-stopped
    # 加入指定网络
    networks:
      - MyNetwork
    # 以 Compose 配置文件为中心的相对路径作为数据卷挂载到容器。
    volumes:
      - ./data:/data:rw
      # - ./conf/redis.conf:/etc/redis/redis.conf
    command: redis-server --requirepass 123456
    ports:
      - 6379:6379

networks:
  MyNetwork:
    external: true
# docker-compose build --no-cache
# docker-compose up -d
